language: java
jdk: oraclejdk8

after_success:
  - mv ./target/multichat-0.0.1-SNAPSHOT.jar .
  - rm -r ./src
  - rm -r ./target
  - rm ./pom.xml

deploy:
  provider: azure_web_apps
  on: master
  verbose: true
  skip_cleanup: true